# use https://lint.travis-ci.org/ to check validity
# use https://gist.github.com/tgrrtt/96b206c22b82f92ce563 to see examples
# use https://github.com/travis-ci/artifacts#installation for artifacts guide
# make the s3 directory public in aws give access to the artifacts

language: java
sudo: false
script: ant dist
jdk:
- oraclejdk8

deploy:
  provider: s3
  deployment_group: s3 group
  on:
    # experiment to 'always' deploy so the results of junit can always be seen
    # even if they fail
    # condition: true
    all_branches: true
  access_key_id: AKIAJGL6AEN37LDO3N7A
  secret_access_key:
    secure: W8HJgOUEt/d+C+1zeD+Znum0Yso8LLZ9eV8rUrYH2MIVl5dCcH+WaGwhLompNOAUbWYhjcr8Rn/SLqvCEcVWe651R4pwHiD0KNfDUwp907Ic/efluCd/T6RjCG7pjbE5bdPIeZjyupMcZMHU4aW7YN6QE1UlVPhDFKQlU84iGsc=
  bucket: mrl-bucket-01
  skip_cleanup: true
  # upload-dir: current
  # travis will only copy 1 dir
  local_dir: dist
  # local_dir: build/report
  acl: 'public_read'

addons:
  artifacts:
    bucket: mrl-bucket-02    
    debug: true
    # s3_region: us-west-1 | defaults to us-east-1
    key:
      secure: "HPVRrxMM0NCjH3S8VI1eG0Wl9diyiGZu9n8NRnGpyxXyjplAM+7p9ezGf6i3a+sdTashtjeLb5dpRruk4Hd5+Hn6V6QQahVrI82Q8bkcy5LQsnea2IBAHEMxQZMjFJhh4STUrX7SvRABHCYGWn1sCupauB00EhDjvfqWMCrEQF8="
    secret:
      secure: "Qs0Hh0yLdrqRn4PdkX+Agz3AVuaYANDuhYzwqHux/aJEp0WAu2cf4B/WECtf8AHAJMP9MpXGsRD3PnKNwQOqO93yjydLcFUhAhUJW9h9SfOsXmeLYO1ZO4dGHV4ODQtQdE92S8Amin/znK9PEl1tO8RYaTcxFfe71YbYHftPPVQ="    
    paths:
    # arbitrary shell commands are supported, but the output should be
    # converted to a ':'-delimited string.
    - $(ls build/report/*.xml | tr "\n" ":")
    # singular paths work fine, too
    - build/lib/myrobotlab.jar  
